connection = ActiveRecord::Base.connection()
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('1', '1');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('1', '2');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('2', '2');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('3', '2');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('4', '2');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('4', '3');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('5', '4');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('6', '4');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('7', '4');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('7', '5');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('8', '4');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('8', '5');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('9', '6');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('9', '4');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('10', '7');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('10', '4');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('11', '4');")
connection.execute("INSERT INTO `vocab_development`.`word_roots_words` (`word_id`, `word_root_id`) VALUES ('11', '8');")

