require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AnswersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Answer. As you add validations to Answer, be sure to
  # adjust the attributes here as well.
  let (:lesson){ FactoryGirl.create(:lesson_no_call_backs) }
  let (:course) { FactoryGirl.create(:course) }
  let (:answer_option) { FactoryGirl.create(:answer_option) }
  let (:lesson_module){ FactoryGirl.create(:lesson_module) }
  let (:question){ FactoryGirl.create(:question) }
  let (:user){ FactoryGirl.create(:user) }
  let(:valid_attributes) {
    {
        question_id: question.id,
        user_id: user.id,
        time_to_complete: 10,
        correct: true
    }
  }

  let(:invalid_attributes) {
    {
        question_id: nil,
        user_id: nil,
        time_to_complete: nil,
        correct: nil
    }
  }

  before(:each) {
    allow_any_instance_of(Question).to receive(:create_answer_options).and_return(true)
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnswersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all answers as @answers" do
      answer = Answer.create! valid_attributes
      get :index, {question_id: answer.question.id, lesson_module_id: answer.question.lesson_module.id, lesson_id: answer.question.lesson_module.lesson.id, course_id: answer.question.lesson_module.lesson.course.id}, valid_session
      expect(assigns(:answers)).to eq([answer])
    end
  end

  describe "GET #show" do
    it "assigns the requested answer as @answer" do
      answer = Answer.create! valid_attributes
      get :show, {:id => answer.to_param, question_id: answer.question.id, lesson_module_id: answer.question.lesson_module.id, lesson_id: answer.question.lesson_module.lesson.id, course_id: answer.question.lesson_module.lesson.course.id}, valid_session
      expect(assigns(:answer)).to eq(answer)
    end
  end

  describe "GET #new" do
    it "assigns a new answer as @answer" do
      get :new, {question_id: question.id, lesson_module_id: lesson_module.id, lesson_id: lesson.id, course_id: course.id}, valid_session
      expect(assigns(:answer)).to be_a_new(Answer)
    end
  end

  describe "GET #edit" do
    it "assigns the requested answer as @answer" do
      answer = Answer.create! valid_attributes
      get :edit, {:id => answer.to_param, question_id: answer.question.id, lesson_module_id: answer.question.lesson_module.id, lesson_id: answer.question.lesson_module.lesson.id, course_id: answer.question.lesson_module.lesson.course.id}, valid_session
      expect(assigns(:answer)).to eq(answer)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Answer" do
        expect {
          post :create, {:answer => valid_attributes, question_id: question.id, lesson_module_id: lesson_module.id, lesson_id: lesson.id, course_id: course.id}, valid_session
        }.to change(Answer, :count).by(1)
      end

      it "assigns a newly created answer as @answer" do
        post :create, {:answer => valid_attributes, question_id: question.id, lesson_module_id: lesson_module.id, lesson_id: lesson.id, course_id: course.id}, valid_session
        expect(assigns(:answer)).to be_a(Answer)
        expect(assigns(:answer)).to be_persisted
      end

      it "redirects to the created answer" do
        post :create, {:answer => valid_attributes, question_id: question.id, lesson_module_id: lesson_module.id, lesson_id: lesson.id, course_id: course.id}, valid_session
        expect(response).to redirect_to(course_lesson_lesson_module_question_answer_path(Answer.last, question_id: Answer.last.question.id, lesson_module_id: Answer.last.question.lesson_module.id, lesson_id: Answer.last.question.lesson_module.lesson.id, course_id: Answer.last.question.lesson_module.lesson.course.id))
      end
    end

    context "with invalid params" do
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
            correct: false
        }
      }

      it "assigns the requested answer as @answer" do
        answer = Answer.create! valid_attributes
        put :update, {:id => answer.to_param, :answer => valid_attributes, question_id: answer.question.id, lesson_module_id: answer.question.lesson_module.id, lesson_id: answer.question.lesson_module.lesson.id, course_id: answer.question.lesson_module.lesson.course.id}, valid_session
        expect(assigns(:answer)).to eq(answer)
      end

      it "redirects to the answer" do
        answer = Answer.create! valid_attributes
        put :update, {:id => answer.to_param, :answer => valid_attributes, question_id: answer.question.id, lesson_module_id: answer.question.lesson_module.id, lesson_id: answer.question.lesson_module.lesson.id, course_id: answer.question.lesson_module.lesson.course.id}, valid_session
        expect(response).to redirect_to(course_lesson_lesson_module_question_answer_path(answer, question_id: answer.question.id, lesson_module_id: answer.question.lesson_module.id, lesson_id: answer.question.lesson_module.lesson.id, course_id: answer.question.lesson_module.lesson.course.id))
      end
    end

    context "with invalid params" do
      it "assigns the answer as @answer" do
        answer = Answer.create! valid_attributes
        put :update, {:id => answer.to_param, :answer => invalid_attributes, question_id: answer.question.id, lesson_module_id: answer.question.lesson_module.id, lesson_id: answer.question.lesson_module.lesson.id, course_id: answer.question.lesson_module.lesson.course.id}, valid_session
        expect(assigns(:answer)).to eq(answer)
      end

      it "re-renders the 'edit' template" do
        answer = Answer.create! valid_attributes
        put :update, {:id => answer.to_param, :answer => invalid_attributes, question_id: answer.question.id, lesson_module_id: answer.question.lesson_module.id, lesson_id: answer.question.lesson_module.lesson.id, course_id: answer.question.lesson_module.lesson.course.id}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested answer" do
      answer = Answer.create! valid_attributes
      expect {
        delete :destroy, {:id => answer.to_param, question_id: answer.question.id, lesson_module_id: answer.question.lesson_module.id, lesson_id: answer.question.lesson_module.lesson.id, course_id: answer.question.lesson_module.lesson.course.id}, valid_session
      }.to change(Answer, :count).by(-1)
    end

    it "redirects to the answers list" do
      answer = Answer.create! valid_attributes
      delete :destroy, {:id => answer.to_param, question_id: answer.question.id, lesson_module_id: answer.question.lesson_module.id, lesson_id: answer.question.lesson_module.lesson.id, course_id: answer.question.lesson_module.lesson.course.id}, valid_session
      expect(response).to redirect_to(course_lesson_lesson_module_question_answers_path(question: answer.question, lesson_module_id: answer.question.lesson_module, lesson_id: answer.question.lesson_module.lesson.id, course_id: answer.question.lesson_module.lesson.course.id))
    end
  end

end
