require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LessonExtensionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # LessonExtension. As you add validations to LessonExtension, be sure to
  # adjust the attributes here as well.
  let (:lesson){ FactoryGirl.create(:lesson_no_call_backs) }
  let (:lesson_update){ FactoryGirl.create(:lesson_no_call_backs) }
  let(:valid_attributes) {
    {
        lesson_id: lesson.id
    }
  }

  let(:invalid_attributes) {
    {
        lesson_id: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LessonExtensionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all lesson_extensions as @lesson_extensions" do
      lesson_extension = LessonExtension.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:lesson_extensions)).to eq([lesson_extension])
    end
  end

  describe "GET #show" do
    it "assigns the requested lesson_extension as @lesson_extension" do
      lesson_extension = LessonExtension.create! valid_attributes
      get :show, {:id => lesson_extension.to_param}, valid_session
      expect(assigns(:lesson_extension)).to eq(lesson_extension)
    end
  end

  describe "GET #new" do
    it "assigns a new lesson_extension as @lesson_extension" do
      get :new, {}, valid_session
      expect(assigns(:lesson_extension)).to be_a_new(LessonExtension)
    end
  end

  describe "GET #edit" do
    it "assigns the requested lesson_extension as @lesson_extension" do
      lesson_extension = LessonExtension.create! valid_attributes
      get :edit, {:id => lesson_extension.to_param}, valid_session
      expect(assigns(:lesson_extension)).to eq(lesson_extension)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new LessonExtension" do
        expect {
          post :create, {:lesson_extension => valid_attributes}, valid_session
        }.to change(LessonExtension, :count).by(1)
      end

      it "assigns a newly created lesson_extension as @lesson_extension" do
        post :create, {:lesson_extension => valid_attributes}, valid_session
        expect(assigns(:lesson_extension)).to be_a(LessonExtension)
        expect(assigns(:lesson_extension)).to be_persisted
      end

      it "redirects to the created lesson_extension" do
        post :create, {:lesson_extension => valid_attributes}, valid_session
        expect(response).to redirect_to(LessonExtension.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved lesson_extension as @lesson_extension" do
        post :create, {:lesson_extension => invalid_attributes}, valid_session
        expect(assigns(:lesson_extension)).to be_a_new(LessonExtension)
      end

      it "re-renders the 'new' template" do
        post :create, {:lesson_extension => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
            lesson_id: lesson_update.id
        }
      }

      it "updates the requested lesson_extension" do
        lesson_extension = LessonExtension.create! valid_attributes
        put :update, {:id => lesson_extension.to_param, :lesson_extension => new_attributes}, valid_session
        lesson_extension.reload
        expect(assigns(:lesson_extension).attributes.symbolize_keys[:extension_date]).to eq(new_attributes[:extension_date])
      end

      it "assigns the requested lesson_extension as @lesson_extension" do
        lesson_extension = LessonExtension.create! valid_attributes
        put :update, {:id => lesson_extension.to_param, :lesson_extension => valid_attributes}, valid_session
        expect(assigns(:lesson_extension)).to eq(lesson_extension)
      end

      it "redirects to the lesson_extension" do
        lesson_extension = LessonExtension.create! valid_attributes
        put :update, {:id => lesson_extension.to_param, :lesson_extension => valid_attributes}, valid_session
        expect(response).to redirect_to(lesson_extension)
      end
    end

    context "with invalid params" do
      it "assigns the lesson_extension as @lesson_extension" do
        lesson_extension = LessonExtension.create! valid_attributes
        put :update, {:id => lesson_extension.to_param, :lesson_extension => invalid_attributes}, valid_session
        expect(assigns(:lesson_extension)).to eq(lesson_extension)
      end

      it "re-renders the 'edit' template" do
        lesson_extension = LessonExtension.create! valid_attributes
        put :update, {:id => lesson_extension.to_param, :lesson_extension => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested lesson_extension" do
      lesson_extension = LessonExtension.create! valid_attributes
      expect {
        delete :destroy, {:id => lesson_extension.to_param}, valid_session
      }.to change(LessonExtension, :count).by(-1)
    end

    it "redirects to the lesson_extensions list" do
      lesson_extension = LessonExtension.create! valid_attributes
      delete :destroy, {:id => lesson_extension.to_param}, valid_session
      expect(response).to redirect_to(lesson_extensions_url)
    end
  end

end
