require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WordVideosController, type: :controller do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # WordVideo. As you add validations to WordVideo, be sure to
  # adjust the attributes here as well.
  let(:word) { FactoryGirl.create(:word) }
  let(:valid_attributes) {
    {
        video_link: "http://www.google.com",
        video_description: "Check out that google ",
        word_id: word.id
    }
  }

  let(:invalid_attributes) {
    {
        video_link: "", #must be longer than 8 characters
        video_description: "" #must be longer than 4 characters
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WordVideosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all word_videos as @word_videos" do
      word_video = WordVideo.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:word_videos)).to eq([word_video])
    end
  end

  describe "GET #show" do
    it "assigns the requested word_video as @word_video" do
      word_video = WordVideo.create! valid_attributes
      get :show, {:id => word_video.to_param}, valid_session
      expect(assigns(:word_video)).to eq(word_video)
    end
  end

  describe "GET #new" do
    it "assigns a new word_video as @word_video" do
      get :new, {}, valid_session
      expect(assigns(:word_video)).to be_a_new(WordVideo)
    end
  end

  describe "GET #edit" do
    it "assigns the requested word_video as @word_video" do
      word_video = WordVideo.create! valid_attributes
      get :edit, {:id => word_video.to_param}, valid_session
      expect(assigns(:word_video)).to eq(word_video)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new WordVideo" do
        expect {
          post :create, {:word_video => valid_attributes}, valid_session
        }.to change(WordVideo, :count).by(1)
      end

      it "assigns a newly created word_video as @word_video" do
        post :create, {:word_video => valid_attributes}, valid_session
        expect(assigns(:word_video)).to be_a(WordVideo)
        expect(assigns(:word_video)).to be_persisted
      end

      it "redirects to the created word_video" do
        post :create, {:word_video => valid_attributes}, valid_session
        expect(response).to redirect_to(word)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved word_video as @word_video" do
        post :create, {:word_video => invalid_attributes}, valid_session
        expect(assigns(:word_video)).to be_a_new(WordVideo)
      end

      it "re-renders the 'new' template" do
        post :create, {:word_video => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
            video_link: "http://www.google.oi"
        }
      }

      it "updates the requested word_video" do
        word_video = WordVideo.create! valid_attributes
        put :update, {:id => word_video.to_param, :word_video => new_attributes}, valid_session
        word_video.reload
        expect(assigns(:word_video).attributes.symbolize_keys[:video_link]).to eq(new_attributes[:video_link])
      end

      it "assigns the requested word_video as @word_video" do
        word_video = WordVideo.create! valid_attributes
        put :update, {:id => word_video.to_param, :word_video => valid_attributes}, valid_session
        expect(assigns(:word_video)).to eq(word_video)
      end

      it "redirects to the word_video" do
        word_video = WordVideo.create! valid_attributes
        put :update, {:id => word_video.to_param, :word_video => valid_attributes}, valid_session
        expect(response).to redirect_to(word)
      end
    end

    context "with invalid params" do
      it "assigns the word_video as @word_video" do
        word_video = WordVideo.create! valid_attributes
        put :update, {:id => word_video.to_param, :word_video => invalid_attributes}, valid_session
        expect(assigns(:word_video)).to eq(word_video)
      end

      it "re-renders the 'edit' template" do
        word_video = WordVideo.create! valid_attributes
        put :update, {:id => word_video.to_param, :word_video => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested word_video" do
      word_video = WordVideo.create! valid_attributes
      expect {
        delete :destroy, {:id => word_video.to_param}, valid_session
      }.to change(WordVideo, :count).by(-1)
    end

    it "redirects to the word_videos list" do
      word_video = WordVideo.create! valid_attributes
      delete :destroy, {:id => word_video.to_param}, valid_session
      expect(response).to redirect_to(word_videos_url)
    end
  end

end
