require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WordRootsController, type: :controller do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # WordRoot. As you add validations to WordRoot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
        root_name: 'cron',
        root_definition: 'having to do with time'
    }
  }

  let(:invalid_attributes) {
    {
        root_name: 'abcdefghijk', #greater than 10
        root_definition: 'ab' #less than 4
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WordRootsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all word_roots as @word_roots" do
      word_root = WordRoot.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:word_roots)).to eq([word_root])
    end
  end

  describe "GET #show" do
    it "assigns the requested word_root as @word_root" do
      word_root = WordRoot.create! valid_attributes
      get :show, {:id => word_root.to_param}, valid_session
      expect(assigns(:word_root)).to eq(word_root)
    end
  end

  describe "GET #new" do
    it "assigns a new word_root as @word_root" do
      get :new, {}, valid_session
      expect(assigns(:word_root)).to be_a_new(WordRoot)
    end
  end

  describe "GET #edit" do
    it "assigns the requested word_root as @word_root" do
      word_root = WordRoot.create! valid_attributes
      get :edit, {:id => word_root.to_param}, valid_session
      expect(assigns(:word_root)).to eq(word_root)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new WordRoot" do
        expect {
          post :create, {:word_root => valid_attributes}, valid_session
        }.to change(WordRoot, :count).by(1)
      end

      it "assigns a newly created word_root as @word_root" do
        post :create, {:word_root => valid_attributes}, valid_session
        expect(assigns(:word_root)).to be_a(WordRoot)
        expect(assigns(:word_root)).to be_persisted
      end

      it "redirects to the created word_root" do
        post :create, {:word_root => valid_attributes}, valid_session
        expect(response).to redirect_to(WordRoot.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved word_root as @word_root" do
        post :create, {:word_root => invalid_attributes}, valid_session
        expect(assigns(:word_root)).to be_a_new(WordRoot)
      end

      it "re-renders the 'new' template" do
        post :create, {:word_root => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
            root_definition: 'having to do with time travel'
        }
      }

      it "updates the requested word_root" do
        word_root = WordRoot.create! valid_attributes
        put :update, {:id => word_root.to_param, :word_root => new_attributes}, valid_session
        word_root.reload
        expect(assigns(:word_root).attributes.symbolize_keys[:root_definition]).to eq(new_attributes[:root_definition])
      end

      it "assigns the requested word_root as @word_root" do
        word_root = WordRoot.create! valid_attributes
        put :update, {:id => word_root.to_param, :word_root => valid_attributes}, valid_session
        expect(assigns(:word_root)).to eq(word_root)
      end

      it "redirects to the word_root" do
        word_root = WordRoot.create! valid_attributes
        put :update, {:id => word_root.to_param, :word_root => valid_attributes}, valid_session
        expect(response).to redirect_to(word_root)
      end
    end

    context "with invalid params" do
      it "assigns the word_root as @word_root" do
        word_root = WordRoot.create! valid_attributes
        put :update, {:id => word_root.to_param, :word_root => invalid_attributes}, valid_session
        expect(assigns(:word_root)).to eq(word_root)
      end

      it "re-renders the 'edit' template" do
        word_root = WordRoot.create! valid_attributes
        put :update, {:id => word_root.to_param, :word_root => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested word_root" do
      word_root = WordRoot.create! valid_attributes
      expect {
        delete :destroy, {:id => word_root.to_param}, valid_session
      }.to change(WordRoot, :count).by(-1)
    end

    it "redirects to the word_roots list" do
      word_root = WordRoot.create! valid_attributes
      delete :destroy, {:id => word_root.to_param}, valid_session
      expect(response).to redirect_to(word_roots_url)
    end
  end

end
