require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WordFormsController, type: :controller do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # WordForm. As you add validations to WordForm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
        :associated_word => "Associated Word",
    }
  }

  let(:invalid_attributes) {
    {
        :associated_word => "" #must be greater than 1 characters
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WordFormsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all word_forms as @word_forms" do
      word_form = WordForm.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:word_forms)).to eq([word_form])
    end
  end

  describe "GET #show" do
    it "assigns the requested word_form as @word_form" do
      word_form = WordForm.create! valid_attributes
      get :show, {:id => word_form.to_param}, valid_session
      expect(assigns(:word_form)).to eq(word_form)
    end
  end

  describe "GET #new" do
    it "assigns a new word_form as @word_form" do
      get :new, {}, valid_session
      expect(assigns(:word_form)).to be_a_new(WordForm)
    end
  end

  describe "GET #edit" do
    it "assigns the requested word_form as @word_form" do
      word_form = WordForm.create! valid_attributes
      get :edit, {:id => word_form.to_param}, valid_session
      expect(assigns(:word_form)).to eq(word_form)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new WordForm" do
        expect {
          post :create, {:word_form => valid_attributes}, valid_session
        }.to change(WordForm, :count).by(1)
      end

      it "assigns a newly created word_form as @word_form" do
        post :create, {:word_form => valid_attributes}, valid_session
        expect(assigns(:word_form)).to be_a(WordForm)
        expect(assigns(:word_form)).to be_persisted
      end

      it "redirects to the created word_form" do
        post :create, {:word_form => valid_attributes}, valid_session
        expect(response).to redirect_to(WordForm.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved word_form as @word_form" do
        post :create, {:word_form => invalid_attributes}, valid_session
        expect(assigns(:word_form)).to be_a_new(WordForm)
      end

      it "re-renders the 'new' template" do
        post :create, {:word_form => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
            associated_word: "TEST"
        }
      }

      it "updates the requested word_form" do
        word_form = WordForm.create! valid_attributes
        put :update, {:id => word_form.to_param, :word_form => new_attributes}, valid_session
        word_form.reload
        expect(assigns(:word_form).attributes.symbolize_keys[:associated_word]).to eq(new_attributes[:associated_word])
      end

      it "assigns the requested word_form as @word_form" do
        word_form = WordForm.create! valid_attributes
        put :update, {:id => word_form.to_param, :word_form => valid_attributes}, valid_session
        expect(assigns(:word_form)).to eq(word_form)
      end

      it "redirects to the word_form" do
        word_form = WordForm.create! valid_attributes
        put :update, {:id => word_form.to_param, :word_form => valid_attributes}, valid_session
        expect(response).to redirect_to(word_form)
      end
    end

    context "with invalid params" do
      it "assigns the word_form as @word_form" do
        word_form = WordForm.create! valid_attributes
        put :update, {:id => word_form.to_param, :word_form => invalid_attributes}, valid_session
        expect(assigns(:word_form)).to eq(word_form)
      end

      it "re-renders the 'edit' template" do
        word_form = WordForm.create! valid_attributes
        put :update, {:id => word_form.to_param, :word_form => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested word_form" do
      word_form = WordForm.create! valid_attributes
      expect {
        delete :destroy, {:id => word_form.to_param}, valid_session
      }.to change(WordForm, :count).by(-1)
    end

    it "redirects to the word_forms list" do
      word_form = WordForm.create! valid_attributes
      delete :destroy, {:id => word_form.to_param}, valid_session
      expect(response).to redirect_to(word_forms_url)
    end
  end

end
